### ISSUE TITLE
tag the release

### ISSUE THREAD

**Issue by chenrui333** [nwiizo/tfocus#3]
👋 thanks for the project, can you maybe tag the release? It would help distribute the project. :) Thanks!

**Comment by nwiizo** [comment]
Hi 👋 Thanks for your interest! 
Yes, you can already install tfocus via `cargo install tfocus`, but you're right - having release tags on GitHub would be helpful. I'll update and create a release tag shortly. 😊

**Comment by nwiizo** [comment]
I'll set up automated releases using cargo-release soon. 😊
https://github.com/crate-ci/cargo-release
